### PR TITLE
Fixed Allowed Documents mapping for Stripe Identity

### LINKED ISSUE #230: Mistake in the mapping of allowed documents for verificationSessions/Reports
The allowed documents for a verificationSession are Passport, id_card and driving_license but id_card is mapped as id_number in StripeVerificationReportOptionsDocumentAllowedType and StripeVerificationSessionOptionsDocumentAllowedType enums.

https://stripe.com/docs/api/identity/verification_sessions/object#identity_verification_session_object-options-document-allowed_types

### PR DESCRIPTION
**Pull request by dbossotto**
Fix #230

### CODE REVIEW

File: Sources/StripeKit/Identity/VerificationSession/VerificationSession.swift [hunk 1]
```diff
@@ -103,7 +103,7 @@ public enum StripeVerificationSessionOptionsDocumentAllowedType: String, StripeM
     /// Passport document type.
     case passport
     /// ID card document type.
-    case idNumber = "id_number"
+    case idNumber = "id_card"
```
Comment (Andrewangeta) [inline Sources/StripeKit/Identity/VerificationSession/VerificationSession.swift:106]: Can you change the name of the enum here as well?

**Review by Andrewangeta — CHANGES_REQUESTED** [review]

**Comment by dbossotto** [comment]
I've pushed a new commit to implement the changes you requested:
    case idCard = "id_card"

**Review by Andrewangeta — APPROVED** [review]
